# Generated by Django 4.2.2 on 2023-07-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Электронная почта')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=1, verbose_name='Пол')),
            ],
        ),
    ]
